// COmmonJS, every file is modue (by default)
// Modules - Encapsulated Code (only shar minimum)
const names = require('./4-names')
const sayHi = require('./5-utils')
const data = require('./6-alternative-flavor')
require('./7-mind-grenade')

// console.log(data)
sayHi('Kapil')
sayHi(names.john)
sayHi(names.petter)